### ISSUE TITLE
x-ray-images-enhancement

### ISSUE THREAD

**Issue by nedimmuzoglu** [asalmada/x-ray-images-enhancement#19]
Hi Mr. André Almada

I am really interested your valuable  Xray enhancement repository. But unfortunately I could not use it correctly.Do you have youtube video about this subject.
sincerly.

**Comment by eduardogmisiuk** [comment]
Hi @nedimmuzoglu , there were some problems with our setup. Please refer to the latest updates I made to make the project work.
