### ISSUE TITLE
Incorrect requirements.txt due to ubuntu bugs

### ISSUE THREAD

**Issue by superp0tat0** [asalmada/x-ray-images-enhancement#22]
Please remove pkg-resources==0.0.0 from requirements.txt

Source: https://stackoverflow.com/questions/39577984/what-is-pkg-resources-0-0-0-in-output-of-pip-freeze-command

**Comment by eduardogmisiuk** [comment]
Thank you @superp0tat0 for your input. I've fixed the problems with the installation. Hope it helps!
